//   --------- USAR INTERFACES --- (en carpeta modelos) ---------
//   export interface LoginData {
//     user: string;
//     password: string;
//   }

// QUE TODO SEA RESPONSIVE

// DRAG DROP ENTRE TIPO SKILL, PARA MODIFICAR LA UBICACION





// CONSULTAS : 

// Cambiar nombre de proyecto de Spring Boot? ("segunda")

// Se ve el token en el session storage





// SI QUEDA TIEMPO :

// **LISTO (con confirm, si queda tiempo hacer modal)
// PREGUNTAR ANTES DE ELIMINAR. MODAL- ¿QUIERES ELIMINAR {{OBJETO.NOMBRE}}?

// OPCION DE QUE UN USUARIO SE REGISTRE, 
// QUE NO TENGA PERMISOS PARA EDITAR, 
// PERO QUE SI PUEDA CREAR UN PORTFOLIO NUEVO CON SUS DATOS,
// VER COMO SERÍA EN BACKEND, PERMISOS Y CONTRASEÑA CON TOKEN.

// MODALES QUE AVISE SI ESTÁ VACÍO, O ESTILOS, CUANDO CREO ESTUDIO/EXP/IDIOMA 
// Cambiar alerts, confirms y prompts

// One to many, Many to one -después hacerlo con personas-

// BOTON DE RESTAURAR DATOS,
// ELIMINAR TODOS LOS REGISTROS
// METODO POST PARA TODOS





// RESUELTAS :

// **LISTO - Error 403 cuando recién inicio sesión, al actualizar la página si funciona

// **LISTO - HACERLO RESPONSIVE
// FOOTER MAS ANCHO WIDHT (CELU)
// MODALES SKILLS RESPONSIVE

// **LISTO - INVESTIGAR FUNCION DRAG AND DROP.

// **LISTO - SECCION DE CONTACTAME, QUE ENVIE UN MAIL ?

// **LISTO - INVESTIGAR COMO SUBIR FOTOS, PARA PODER EDITAR,
// AGREGAR BOTON DE EDITAR, Y QUE HAYA COMO UN INPUT PARA SUBIR LA IMAGEN.
// O SINO UN INPUT OCULTO PARA ESCRIBIR LA RUTA DE ASSETS.

// **LISTO - SET ORDEN ULTIMO CUANDO CREO UN NUEVO REGISTRO

// **LISTO - QUE NO ME DEJE AGREGAR ESTUDIOS/EXP/IDIOMAS VACIOS

// **LISTO - SUBIR IMAGENES DE LOGOS EN HISTORY (ESTUDIOS, EXP, IDIOMAS),
// O QUE ESTÉ LA OPCIÓN DE QUE QUEDE VACÍO

// **LISTO - One to many, Many to one. (Skills, para poder clasificarlas)

// **LISTO - SKILLS QUE NO SE MUEVAN SI NO ESTOY LOGUEADO

// **LISTO - AJUSTAR SEPARACION ENTRE ELEMENTOS (EST, PROY, IDIOMAS) 
// EN EL CELU SE VEN MUY PEGADOS

// **LISTO - AGREGAR BOTON DE EDICION A LAS OTRAS IMAGENES

// **LISTO - ANIMACION MIENTRAS CARGA **FALTA QUE NO SE VEA LO DEMAS (SUBTITULOS Y ESO)

// **LISTO - PROYECTOS, AGREGAR SECCION DE TECNOLOGIAS CON ICONOS
// AGREGAR LINK A GITHUB / Y PAGINA SI EXISTIERA
// Nombre, Fecha, Descripción, Link, Imagen

// **LISTO - AGREGAR "ORDEN" A TIPOSKILL EN SPRING BOOT, PARA PODER MANEJARLO MEJOR
// METODO PUT EN TIPOSKILL PARA PODER MODIFICAR **Conviene que desde el front se puedan agregar/modificar??