
// ------ INVESTIGAR : 

// Cambiar nombre de proyecto de Spring Boot? ("segunda")

// Se ve el token en el session storage, como ocultarlo?





// ------ SI QUEDA TIEMPO :

// USAR INTERFACES O CLASES (no usar tipo :any)

// AGREGAR VALIDACIONES

// CAMBIAR ALERTS, CONFIRMS Y PROMPTS POR MODALES PARA QUE SE VEA MAS LINDO

// ONE TO MANY - HACERLO CON PERSONAS EN BACKEND (Estudios, Experiencias, Idiomas, etc)

// BOTON DE RESTAURAR DATOS. ELIMINAR TODOS LOS REGISTROS Y METODO POST PARA TODOS?

// OPCION DE QUE UN USUARIO SE REGISTRE Y QUE NO TENGA PERMISOS PARA EDITAR, 
// PERO QUE SI PUEDA CREAR UN PORTFOLIO NUEVO CON SUS DATOS,
// VER COMO SERÍA EN BACKEND, PERMISOS Y CONTRASEÑA CON TOKEN.

